language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - release
  - tip

install:
  - go get -v github.com/golang/dep/cmd/dep
  - cd $GOPATH/src/github.com/golang/dep/cmd/dep && git checkout tags/v0.4.1 && go install
  - cd - && dep ensure

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false
